# Generated by Django 3.0 on 2022-05-25 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='referrals',
        ),
    ]
