# Generated by Django 3.0 on 2022-05-25 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_referrals'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subset', to=settings.AUTH_USER_MODEL),
        ),
    ]
