# Generated by Django 3.0 on 2022-05-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_referral'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_point', models.FloatField(default=1)),
                ('subset_point', models.FloatField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='user',
            old_name='balance',
            new_name='claim_point',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='referral_point',
            new_name='subset_point',
        ),
    ]
