# Generated by Django 3.0 on 2022-06-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_systemsetting_about_us'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='text',
            new_name='question',
        ),
        migrations.AddField(
            model_name='faq',
            name='answer',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
