# Generated by Django 3.0 on 2022-06-03 12:47

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20220603_1230'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Socials',
        ),
        migrations.AddField(
            model_name='globalinfo',
            name='extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='globalinfo',
            name='socials',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(default=dict), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='globalinfo',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='globalinfo',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='claim_period',
            field=models.IntegerField(blank=True, default=600),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='claim_point',
            field=models.FloatField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='subset_point',
            field=models.FloatField(blank=True, default=1),
        ),
    ]
