# Generated by Django 3.0 on 2022-06-03 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20220603_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalinfo',
            name='title',
        ),
        migrations.RemoveField(
            model_name='globalinfo',
            name='value',
        ),
    ]
