# Generated by Django 3.0 on 2022-06-03 13:39

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20220603_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalinfo',
            name='socials',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(default=dict), blank=True, default=list, null=True, size=None),
        ),
    ]
