# Generated by Django 3.0 on 2022-06-03 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0016_auto_20220603_1327"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="globalinfo",
            name="socials",
        ),
    ]
