# Generated by Django 3.0 on 2022-06-07 17:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_globalinfo_socials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsetting',
            name='subset_point',
            field=models.FloatField(blank=True, default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
